const CHILL = 'CHILL';
const NOT_CHILL = 'NOT_CHILL';
const REQUEST_API = 'REQUEST_API';
const REQUEST_FAILURE = 'REQUEST_FAILURE';
const REQUEST_SUCCESS= 'REQUEST_SUCCESS';


export {NOT_CHILL,CHILL,REQUEST_API,REQUEST_FAILURE, REQUEST_SUCCESS}
